version: "3.3"

services:
  nginx:
    image: nginx:1.20-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx:/etc/nginx
      - ./public:/var/www/public

  php-fpm:
    build:
      context: docker/php-fpm
    container_name: php-fpm
    working_dir: /var/www
    environment:
      XDEBUG_TRIGGER: 1
      XDEBUG_CONFIG: 'client_host=172.17.0.1'
      PHP_IDE_CONFIG: 'serverName=rent-a-car'
    volumes:
      - .:/var/www

  db:
    image: mysql:8.0.27
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev_password

volumes:
  db_data:
